LearnThread:LearnThread.cpp
	g++ -std=c++11 -O2 -o LearnThread LearnThread.cpp -lpthread
ThreadJoinOrDetach:ThreadJoinOrDetach.cpp
	g++ -std=c++11 -O2 -o ThreadJoinOrDetach ThreadJoinOrDetach.cpp -lpthread
ConditionVariable:ConditionVariable.cpp
	g++ -std=c++11 -O2 -o ConditionVariable ConditionVariable.cpp -lpthread
SingleThreadVersion:SingleThreadVersion.cpp
	g++ -std=c++11 -O2 -o SingleThreadVersion SingleThreadVersion.cpp -lpthread
