ClassVirtual:ClassVirtual.cpp
	g++ -O0 -std=c++14 -o $@ $<
BitField:BitField.cpp
	g++ -O0 -std=c++14 -o $@ $<
PureVirtualDesc:PureVirtualDesc.cpp
	g++ -O0 -std=c++14 -o $@ $<
SmartPtr:SmartPtr.cpp
	g++ -O0 -std=c++14 -o $@ $<
