main:main.cpp BB.cpp
	g++ -o $@ $^
memoryKnowledge:memoryKnowledge.cpp
	g++ -g -O0 -std=c++14 -o $@ $<
GrammarKnowledge:GrammarKnowledge.cpp
	g++ -g -O0 -std=c++14 -o $@ $<
StlKnowledge:StlKnowledge.cpp
	g++ -g -O0 -std=c++14 -o $@ $<
ThreadKnowledge:ThreadKnowledge.cpp
	g++ -g -O0 -std=c++14 -o $@ $< -lpthread
ThreadKnowledgeFast:ThreadKnowledge.cpp
	g++ -O2 -std=c++14 -o $@ $< -lpthread
BaseCPPTest:BaseCPPTest.cpp
	g++ -g -O0 -std=c++14 -o $@ $<
RightFunctionInterface:RightFunctionInterface.cpp
	g++ -O2 -std=c++14 -o $@ $<
Quiz:Quiz.cpp
	g++ -O2 -std=c++14 -o $@ $<
ExceptionKnowledge:ExceptionKnowledge.cpp
	g++ -O2 -std=c++14 -o $@ $<
ClassKnowledge:ClassKnowledge.cpp
	g++ -g -O0 -std=c++14 -o $@ $<
HardwareKnowledge:HardwareKnowledge.cpp
	g++ -g -O2 -std=c++14 -o $@ $<
PointerOrReference:PointerOrReference.cpp
	g++ -g -O2 -std=c++14 -o $@ $<
TemplateAndTraits:TemplateAndTraits.cpp
	g++ -g -O2 -std=c++14 -o $@ $<
CppKeywords:CppKeywords.cpp
	g++ -O0 -std=c++14 -o $@ $<
ClassVirtual11:ClassVirtual11.cpp
	g++ -O0 -std=c++14 -o $@ $<
DummyMalloc:DummyMalloc.cpp
	g++ -O0 -std=c++14 -o $@ $<
AlgorithmQuiz:AlgorithmQuiz.cpp
	g++ -O0 -std=c++14 -o $@ $<
CppLambda:CppLambda.cpp
	g++ -O0 -std=c++14 -o $@ $<
TestSetBound:TestSetBound.cpp
	g++ -O3 -std=c++14 -o $@ $<
SetComp:SetComp.cpp
	g++ -O3 -std=c++14 -o $@ $<
