server:main.cpp structHeader.cpp chat_message.h structHeader.h
	g++ -O2 -std=c++14 -o server main.cpp structHeader.cpp -lboost_system -lpthread
client:client.cpp structHeader.cpp chat_message.h structHeader.h
	g++ -O2 -std=c++14 -o client client.cpp structHeader.cpp -lboost_system -lpthread
